### ISSUE TITLE
Flutter project

### ISSUE THREAD

**Issue by mudasirll** [OsamaJaved121/reptel_demo#1]
Hey can we do a meeting?

Need to discuss a project with you

**Comment by mudasirll** [comment]
It's urgent if possible can we do meeting today?

**Comment by OsamaJaved121** [comment]
Hi. I would like to know what do you want to discuss with me and do I know you?

**Comment by mudasirll** [comment]
Yr yh Reptel ka project meny hi doya h Mudasir hou

**Comment by mudasirll** [comment]
03054477065 ispr ap message krlo ap
